#!/usr/bin/env python3
"""Assemble the GitHub Pages site (docs/) and the slide-deck PDF.

1. copies the card files, figures and reference artwork into docs/assets/
2. writes docs/assets/data.js from card/abcd_v2_chips.json and results/*.txt, so
   every number on the site and in the deck traces to a generated file
3. prints docs/deck.html to presentation/ABCD_v2_deck.pdf with headless Chrome
   (skipped if Chrome is not installed) and copies it into docs/assets/

Run after scripts/run_all.sh and scripts/make_figures.py.
"""
import json
import re
import shutil
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS = REPO / "docs"
ASSETS = DOCS / "assets"
ASSETS.mkdir(parents=True, exist_ok=True)
CHROME = Path("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome")

for src in [*(REPO / "card").glob("abcd_v2*"), *(REPO / "figures").glob("*.png"),
            REPO / "reference" / "ABC_v1_stickermule.png", REPO / "reference" / "ABCD_v1.5.png",
            REPO / "measurements" / "batch_template.csv"]:
    shutil.copy2(src, ASSETS / src.name)

spec = json.loads((REPO / "card" / "abcd_v2_chips.json").read_text())

# Where each chip's notation comes from, and why it is on the card.
SOIL_PAGES = {"10R", "2.5YR", "5YR", "7.5YR", "10YR", "2.5Y"}
for c in spec["chips"]:
    hue = c["munsell"].split(" ")[0]
    if c["group"] == "soil":
        c["source"] = f"Munsell Soil-Color Charts, {hue} page: chip and colour name as printed"
    elif c["group"] == "plant":
        c["source"] = f"Hue {hue} is a page of the Munsell Plant Tissue Color Book; value/chroma is a design target"
    elif c["group"] == "calibration":
        c["source"] = "Spread around the Munsell hue circle at the highest chroma that passes the print + sRGB gamut gate"
    else:
        c["source"] = "Munsell neutral value scale"
    if c["munsell"] != c["munsell_requested"]:
        c["source"] += f" (requested {c['munsell_requested']}, chroma reduced to fit the gamut)"
    assert c["group"] != "soil" or hue in SOIL_PAGES, c


def detection(path):
    p = REPO / "results" / path
    if not p.exists():
        return None
    head, rows = "", []
    for line in p.read_text().splitlines():
        if line.startswith("# app:"):
            head = line[2:]
        m = re.match(r"(v[12])_(\S+?)_(plain|cast_blur)\s+card (\S+) ids verified (\d)/4 max corner error (\S+) px (OK|FAIL)", line)
        if m:
            rows.append({"card": m[1], "case": m[2], "fx": m[3], "detected": m[4], "ids": int(m[5]),
                         "err": float(m[6]), "ok": m[7] == "OK"})
    return {"app": head, "rows": rows}


werth = (REPO / "results" / "werth_crosscheck.txt").read_text()
m = re.search(r"(\d+) compared, max per-channel diff (\d+)/255; not in tool: (\[.*\])", werth)
data = {
    "spec": spec,
    "detection": {"before": detection("detection_before.txt"), "after": detection("detection_after.txt")},
    "werth": {"compared": int(m[1]), "maxdiff": int(m[2]), "missing": json.loads(m[3].replace("'", '"'))},
    "aruco": (REPO / "results" / "aruco_ids.txt").read_text().strip().splitlines(),
    "generator": (REPO / "results" / "generator_log.txt").read_text().strip().splitlines()[:9],
    "v1geometry": (REPO / "results" / "v1_geometry.txt").read_text().strip().splitlines(),
}
(ASSETS / "data.js").write_text("// GENERATED by scripts/build_site.py - do not edit\nwindow.ABCD = "
                                + json.dumps(data, indent=0) + ";\n")
print("wrote", ASSETS / "data.js")

if CHROME.exists():
    out = REPO / "presentation" / "ABCD_v2_deck.pdf"
    out.parent.mkdir(exist_ok=True)
    subprocess.run([str(CHROME), "--headless=new", "--disable-gpu", "--no-pdf-header-footer",
                    "--virtual-time-budget=5000", f"--print-to-pdf={out}", (DOCS / "deck.html").as_uri()],
                   check=True, capture_output=True)
    assert out.stat().st_size > 50_000, "deck PDF suspiciously small"
    shutil.copy2(out, ASSETS / out.name)
    print("wrote", out)
else:
    print("Chrome not found: deck PDF not rebuilt")
